"""Board reporting for lifecycle findings (#321).

A non-terminal artifact the close-out (or audit) finds must reach the board as an
issue — not only a log line. These tests inject a fake filer, so no network is
touched, and they are the mutation seam: if the board-reporting is reverted, the
filed-issue assertion fails.
"""

from __future__ import annotations

from pathlib import Path

from governance.lifecycle.audit import Finding
from governance.lifecycle.closeout import closeout
from governance.lifecycle.report import BoardReporter, board_report_findings

import importlib.util as _importlib_util  # noqa: E402

# A bare ``from conftest import ...`` is not safe here: when this suite is
# collected alongside other governance suites, every one of their
# ``tests/conftest.py`` files lands under the same bare module identity
# ``conftest`` in ``sys.modules``, so whichever conftest is imported LAST
# silently wins the name for the rest of collection (issues #699, #702).
# Loading this file's own conftest by absolute path guarantees this module
# always gets ITS directory's conftest regardless of collection order.
_conftest_spec = _importlib_util.spec_from_file_location(
    "governance_lifecycle_tests_conftest", Path(__file__).with_name("conftest.py")
)
_conftest = _importlib_util.module_from_spec(_conftest_spec)
_conftest_spec.loader.exec_module(_conftest)
FakeOps = _conftest.FakeOps
clean_item = _conftest.clean_item
parked_verification = _conftest.parked_verification


class FakeFiler:
    """A board filer that records writes instead of performing them."""

    def __init__(self) -> None:
        self.created: list[dict] = []
        self.comments: list[dict] = []

    def create(self, title: str, body: str, labels) -> int:
        self.created.append({"title": title, "body": body, "labels": list(labels)})
        return 2000 + len(self.created)

    def comment(self, number: int, body: str) -> None:
        self.comments.append({"number": number, "body": body})


def reporter(filer: FakeFiler, tmp_path) -> BoardReporter:
    return BoardReporter(filer, ledger=tmp_path / "reports.json")


def test_a_non_terminal_artifact_files_a_board_finding(tmp_path):
    item = clean_item(branch_deleted=False, lane={"session_id": "s-269", "present": True})
    ops = FakeOps(item, fail=("delete-branch", "reclaim-lane"))
    filer = FakeFiler()
    result = closeout(item, ops, reporter=reporter(filer, tmp_path), apply=True)
    assert not result.ok
    assert filer.created, "a non-terminal artifact must reach the board (mutation seam)"
    titles = " ".join(created["title"] for created in filer.created)
    assert "BRANCH_NOT_DELETED" in titles
    assert "LANE_NOT_RECLAIMED" in titles


def test_repeat_close_outs_do_not_spam_the_board(tmp_path):
    item = clean_item(branch_deleted=False, lane={"session_id": "s-269", "present": True})
    filer = FakeFiler()
    rep = reporter(filer, tmp_path)
    closeout(item, FakeOps(item, fail=("delete-branch", "reclaim-lane")), reporter=rep, apply=True)
    closeout(item, FakeOps(item, fail=("delete-branch", "reclaim-lane")), reporter=rep, apply=True)
    assert len(filer.created) == 2  # one issue per (code, subject), no duplicates


def test_a_dry_run_reports_without_writing(tmp_path):
    item = clean_item(branch_deleted=False, lane={"session_id": "s-269", "present": True})
    filer = FakeFiler()
    result = closeout(
        item,
        FakeOps(item, fail=("delete-branch", "reclaim-lane")),
        reporter=reporter(filer, tmp_path),
        apply=False,
    )
    assert not result.ok
    assert filer.created == []
    assert result.board_reports and all(r.action == "dry-run" for r in result.board_reports)


def test_board_report_findings_is_idempotent_by_fingerprint(tmp_path):
    finding = Finding(
        code="BRANCH_NOT_DELETED",
        subject="#269",
        detail="source branch issue-269 still exists",
    )
    filer = FakeFiler()
    rep = reporter(filer, tmp_path)
    first = board_report_findings([finding], rep, apply=True)
    second = board_report_findings([finding], rep, apply=True)
    assert first and first[0].action == "filed"
    assert second and second[0].action == "deduped"
    assert len(filer.created) == 1


def test_a_parked_verification_files_nothing_on_the_board(tmp_path):
    """A defect report generated by capacity is a false report (#840).

    The board is for defects. A verification the gate never measured is not one:
    no issue may be filed for it, and none may be filed for a companion problem
    either — this item has none, so the filer must stay empty.
    """
    item = clean_item(verify={})
    filer = FakeFiler()
    result = closeout(
        item,
        FakeOps(item, cannot_assess={"record-verification": parked_verification(11)}),
        reporter=reporter(filer, tmp_path),
        apply=True,
    )
    assert result.cannot_assess
    assert filer.created == []
    assert result.board_reports == []


def test_verify_evidence_missing_is_filed_for_an_open_issue(tmp_path):
    """#1266: an OPEN issue's missing-evidence finding is a live board item."""
    finding = Finding(code="VERIFY_EVIDENCE_MISSING", subject="#1300", detail="no attestation")
    filer = FakeFiler()
    rep = reporter(filer, tmp_path)
    result = board_report_findings([finding], rep, apply=True, closed_subjects=frozenset())
    assert result and result[0].action == "filed"
    assert filer.created and "VERIFY_EVIDENCE_MISSING" in filer.created[0]["title"]


def test_verify_evidence_missing_is_not_filed_for_a_closed_issue(tmp_path):
    """#1266: 27 squash merges landed 2026-09-18 and closed 0 issues — the
    auto-filer went on to raise VERIFY_EVIDENCE_MISSING against items already
    closed by hand (#992/#1247/#1251). A subject in ``closed_subjects`` must
    never reach ``filer.create`` for this code."""
    finding = Finding(code="VERIFY_EVIDENCE_MISSING", subject="#992", detail="no attestation")
    filer = FakeFiler()
    rep = reporter(filer, tmp_path)
    result = board_report_findings([finding], rep, apply=True, closed_subjects=frozenset({"#992"}))
    assert result and result[0].action == "obsolete-by-close"
    assert filer.created == [], "a closed issue's evidence gap must not become a new board issue"


def test_a_closed_issues_stale_board_entry_is_resolved_not_left_to_rot(tmp_path):
    """A VERIFY_EVIDENCE_MISSING board issue filed while the item was open must
    be resolved once the item closes, not left open beside an unfileable finding."""
    finding = Finding(code="VERIFY_EVIDENCE_MISSING", subject="#992", detail="no attestation")
    filer = FakeFiler()
    rep = reporter(filer, tmp_path)
    board_report_findings([finding], rep, apply=True, closed_subjects=frozenset())
    assert filer.created  # filed while the item was still open

    # The item's issue closes; the next pass re-observes the same finding.
    second = board_report_findings([finding], rep, apply=True, closed_subjects=frozenset({"#992"}))
    assert second[0].action == "obsolete-by-close"
    # No SECOND issue was created for it.
    assert len(filer.created) == 1


def test_a_forced_file_for_a_closed_issue_is_refused_by_name(tmp_path):
    """Negative control: even asking to file straight into a closed subject's
    board issue must be refused by name, never create one (#1266)."""
    finding = Finding(code="VERIFY_EVIDENCE_MISSING", subject="#1251", detail="no attestation")
    filer = FakeFiler()
    rep = reporter(filer, tmp_path)
    result = board_report_findings([finding], rep, apply=True, closed_subjects=frozenset({"#1251"}))
    assert result[0].action == "obsolete-by-close", "must be refused by name, not silently deduped or filed"
    assert filer.created == []


def test_other_codes_are_unaffected_by_closed_subjects(tmp_path):
    """Only the codes in OPEN_ONLY_CODES are gated on issue state; anything
    else still files normally even against a closed subject."""
    finding = Finding(code="BRANCH_NOT_DELETED", subject="#992", detail="branch still exists")
    filer = FakeFiler()
    rep = reporter(filer, tmp_path)
    result = board_report_findings([finding], rep, apply=True, closed_subjects=frozenset({"#992"}))
    assert result[0].action == "filed"
    assert filer.created


def test_a_park_does_not_excuse_a_finding_that_is_really_broken(tmp_path):
    """A capacity condition must not silence a defect that was actually measured."""
    item = clean_item(verify={}, branch_deleted=False)
    filer = FakeFiler()
    result = closeout(
        item,
        FakeOps(
            item,
            fail=("delete-branch",),
            cannot_assess={"record-verification": parked_verification(11)},
        ),
        reporter=reporter(filer, tmp_path),
        apply=True,
    )
    assert result.verdict == "not-ok"
    assert filer.created, "the measured defect must still reach the board"
    titles = " ".join(created["title"] for created in filer.created)
    assert "BRANCH_NOT_DELETED" in titles
    assert "VERIFY_EVIDENCE_MISSING" not in titles
