"""Board reporting for lifecycle findings (#321).

A non-terminal artifact the close-out (or audit) finds must reach the board as an
issue — not only a log line. These tests inject a fake filer, so no network is
touched, and they are the mutation seam: if the board-reporting is reverted, the
filed-issue assertion fails.
"""

from __future__ import annotations

from pathlib import Path

from governance.lifecycle.audit import Finding
from governance.lifecycle.closeout import closeout
from governance.lifecycle.report import BoardReporter, board_report_findings

import importlib.util as _importlib_util  # noqa: E402

# A bare ``from conftest import ...`` is not safe here: when this suite is
# collected alongside other governance suites, every one of their
# ``tests/conftest.py`` files lands under the same bare module identity
# ``conftest`` in ``sys.modules``, so whichever conftest is imported LAST
# silently wins the name for the rest of collection (issues #699, #702).
# Loading this file's own conftest by absolute path guarantees this module
# always gets ITS directory's conftest regardless of collection order.
_conftest_spec = _importlib_util.spec_from_file_location(
    "governance_lifecycle_tests_conftest", Path(__file__).with_name("conftest.py")
)
_conftest = _importlib_util.module_from_spec(_conftest_spec)
_conftest_spec.loader.exec_module(_conftest)
FakeOps = _conftest.FakeOps
clean_item = _conftest.clean_item
parked_verification = _conftest.parked_verification


class FakeFiler:
    """A board filer that records writes instead of performing them."""

    def __init__(self) -> None:
        self.created: list[dict] = []
        self.comments: list[dict] = []
        self.closed: list[dict] = []

    def create(self, title: str, body: str, labels) -> int:
        self.created.append({"title": title, "body": body, "labels": list(labels)})
        return 2000 + len(self.created)

    def comment(self, number: int, body: str) -> None:
        self.comments.append({"number": number, "body": body})

    def close(self, number: int, comment: str) -> None:
        self.closed.append({"number": number, "comment": comment})


class FailingCloseFiler(FakeFiler):
    """A board whose close is lost — the write that must keep the fingerprint."""

    def close(self, number: int, comment: str) -> None:
        raise RuntimeError("gh issue close failed (1): rate limited")


def reporter(filer: FakeFiler, tmp_path) -> BoardReporter:
    return BoardReporter(filer, ledger=tmp_path / "reports.json")


def ledger_keys(tmp_path) -> set[str]:
    import json

    path = tmp_path / "reports.json"
    return set(json.loads(path.read_text(encoding="utf-8"))) if path.exists() else set()


def test_a_non_terminal_artifact_files_a_board_finding(tmp_path):
    item = clean_item(branch_deleted=False, lane={"session_id": "s-269", "present": True})
    ops = FakeOps(item, fail=("delete-branch", "reclaim-lane"))
    filer = FakeFiler()
    result = closeout(item, ops, reporter=reporter(filer, tmp_path), apply=True)
    assert not result.ok
    assert filer.created, "a non-terminal artifact must reach the board (mutation seam)"
    titles = " ".join(created["title"] for created in filer.created)
    assert "BRANCH_NOT_DELETED" in titles
    assert "LANE_NOT_RECLAIMED" in titles


def test_repeat_close_outs_do_not_spam_the_board(tmp_path):
    item = clean_item(branch_deleted=False, lane={"session_id": "s-269", "present": True})
    filer = FakeFiler()
    rep = reporter(filer, tmp_path)
    closeout(item, FakeOps(item, fail=("delete-branch", "reclaim-lane")), reporter=rep, apply=True)
    closeout(item, FakeOps(item, fail=("delete-branch", "reclaim-lane")), reporter=rep, apply=True)
    assert len(filer.created) == 2  # one issue per (code, subject), no duplicates


def test_a_dry_run_reports_without_writing(tmp_path):
    item = clean_item(branch_deleted=False, lane={"session_id": "s-269", "present": True})
    filer = FakeFiler()
    result = closeout(
        item,
        FakeOps(item, fail=("delete-branch", "reclaim-lane")),
        reporter=reporter(filer, tmp_path),
        apply=False,
    )
    assert not result.ok
    assert filer.created == []
    assert result.board_reports and all(r.action == "dry-run" for r in result.board_reports)


def test_board_report_findings_is_idempotent_by_fingerprint(tmp_path):
    finding = Finding(
        code="BRANCH_NOT_DELETED",
        subject="#269",
        detail="source branch issue-269 still exists",
    )
    filer = FakeFiler()
    rep = reporter(filer, tmp_path)
    first = board_report_findings([finding], rep, apply=True)
    second = board_report_findings([finding], rep, apply=True)
    assert first and first[0].action == "filed"
    assert second and second[0].action == "deduped"
    assert len(filer.created) == 1


def test_a_parked_verification_files_nothing_on_the_board(tmp_path):
    """A defect report generated by capacity is a false report (#840).

    The board is for defects. A verification the gate never measured is not one:
    no issue may be filed for it, and none may be filed for a companion problem
    either — this item has none, so the filer must stay empty.
    """
    item = clean_item(verify={})
    filer = FakeFiler()
    result = closeout(
        item,
        FakeOps(item, cannot_assess={"record-verification": parked_verification(11)}),
        reporter=reporter(filer, tmp_path),
        apply=True,
    )
    assert result.cannot_assess
    assert filer.created == []
    assert result.board_reports == []


def test_verify_evidence_missing_is_filed_for_an_open_issue(tmp_path):
    """#1266: an OPEN issue's missing-evidence finding is a live board item."""
    finding = Finding(code="VERIFY_EVIDENCE_MISSING", subject="#1300", detail="no attestation")
    filer = FakeFiler()
    rep = reporter(filer, tmp_path)
    result = board_report_findings([finding], rep, apply=True, closed_subjects=frozenset())
    assert result and result[0].action == "filed"
    assert filer.created and "VERIFY_EVIDENCE_MISSING" in filer.created[0]["title"]


def test_verify_evidence_missing_is_not_filed_for_a_closed_issue(tmp_path):
    """#1266: 27 squash merges landed 2026-09-18 and closed 0 issues — the
    auto-filer went on to raise VERIFY_EVIDENCE_MISSING against items already
    closed by hand (#992/#1247/#1251). A subject in ``closed_subjects`` must
    never reach ``filer.create`` for this code."""
    finding = Finding(code="VERIFY_EVIDENCE_MISSING", subject="#992", detail="no attestation")
    filer = FakeFiler()
    rep = reporter(filer, tmp_path)
    result = board_report_findings([finding], rep, apply=True, closed_subjects=frozenset({"#992"}))
    assert result and result[0].action == "obsolete-by-close"
    assert filer.created == [], "a closed issue's evidence gap must not become a new board issue"


def test_a_closed_issues_stale_board_entry_is_resolved_not_left_to_rot(tmp_path):
    """A VERIFY_EVIDENCE_MISSING board issue filed while the item was open must
    be resolved once the item closes, not left open beside an unfileable finding."""
    finding = Finding(code="VERIFY_EVIDENCE_MISSING", subject="#992", detail="no attestation")
    filer = FakeFiler()
    rep = reporter(filer, tmp_path)
    board_report_findings([finding], rep, apply=True, closed_subjects=frozenset())
    assert filer.created  # filed while the item was still open

    # The item's issue closes; the next pass re-observes the same finding.
    second = board_report_findings([finding], rep, apply=True, closed_subjects=frozenset({"#992"}))
    assert second[0].action == "obsolete-by-close"
    # No SECOND issue was created for it.
    assert len(filer.created) == 1


def test_a_forced_file_for_a_closed_issue_is_refused_by_name(tmp_path):
    """Negative control: even asking to file straight into a closed subject's
    board issue must be refused by name, never create one (#1266)."""
    finding = Finding(code="VERIFY_EVIDENCE_MISSING", subject="#1251", detail="no attestation")
    filer = FakeFiler()
    rep = reporter(filer, tmp_path)
    result = board_report_findings([finding], rep, apply=True, closed_subjects=frozenset({"#1251"}))
    assert result[0].action == "obsolete-by-close", "must be refused by name, not silently deduped or filed"
    assert filer.created == []


def test_other_codes_are_unaffected_by_closed_subjects(tmp_path):
    """Only the codes in OPEN_ONLY_CODES are gated on issue state; anything
    else still files normally even against a closed subject."""
    finding = Finding(code="BRANCH_NOT_DELETED", subject="#992", detail="branch still exists")
    filer = FakeFiler()
    rep = reporter(filer, tmp_path)
    result = board_report_findings([finding], rep, apply=True, closed_subjects=frozenset({"#992"}))
    assert result[0].action == "filed"
    assert filer.created


def test_a_park_does_not_excuse_a_finding_that_is_really_broken(tmp_path):
    """A capacity condition must not silence a defect that was actually measured."""
    item = clean_item(verify={}, branch_deleted=False)
    filer = FakeFiler()
    result = closeout(
        item,
        FakeOps(
            item,
            fail=("delete-branch",),
            cannot_assess={"record-verification": parked_verification(11)},
        ),
        reporter=reporter(filer, tmp_path),
        apply=True,
    )
    assert result.verdict == "not-ok"
    assert filer.created, "the measured defect must still reach the board"
    titles = " ".join(created["title"] for created in filer.created)
    assert "BRANCH_NOT_DELETED" in titles
    assert "VERIFY_EVIDENCE_MISSING" not in titles


# --- #1299: a filed finding has a terminal move, and it is apply-gated ---------


def _file_then_close_subject(rep: BoardReporter, apply: bool):
    finding = Finding(code="VERIFY_EVIDENCE_MISSING", subject="#1247", detail="no attestation")
    board_report_findings([finding], rep, apply=True, closed_subjects=frozenset())
    return board_report_findings([finding], rep, apply=apply, closed_subjects=frozenset({"#1247"}))


def test_the_terminal_move_closes_the_filed_issue_when_the_subject_closes(tmp_path):
    """#1299: ``resolve`` is the terminal move — the board issue is CLOSED with the
    measurement as evidence, and only then is the fingerprint retired."""
    filer = FakeFiler()
    rep = reporter(filer, tmp_path)
    second = _file_then_close_subject(rep, apply=True)
    assert second[0].action == "obsolete-by-close"
    assert [entry["number"] for entry in filer.closed] == [2001], "the filed issue must be closed, not left open"
    assert "obsolete-by-close" in filer.closed[0]["comment"]
    assert filer.comments == [], "a close carries its own comment; a separate comment would outlive a failed close"
    assert ledger_keys(tmp_path) == set(), "the fingerprint is retired so a genuine recurrence files afresh"


def test_a_dry_run_resolve_writes_nothing_not_even_the_ledger(tmp_path):
    """Measured before #1299: the dry run popped the fingerprint and SAVED the
    ledger while skipping the board write — a dry run that wrote, and a silent
    suppression: the issue stayed open and a recurrence would file a second one."""
    filer = FakeFiler()
    rep = reporter(filer, tmp_path)
    second = _file_then_close_subject(rep, apply=False)
    assert second[0].action == "obsolete-by-close"
    assert filer.closed == [] and filer.comments == []
    assert ledger_keys(tmp_path) == {"lifecycle:VERIFY_EVIDENCE_MISSING:#1247"}, (
        "a dry run must not retire the fingerprint"
    )
    # The dry run only reported it; the apply pass then actually does it.
    assert rep.resolve("lifecycle:VERIFY_EVIDENCE_MISSING:#1247", comment="x", apply=True, close=True)
    assert [entry["number"] for entry in filer.closed] == [2001]
    assert ledger_keys(tmp_path) == set()


def test_a_lost_close_keeps_the_fingerprint_so_the_next_pass_retries(tmp_path):
    """Negative control: the board write runs BEFORE the ledger save, so a failed
    close leaves the fingerprint in place rather than an open issue nobody would
    look at again."""
    filer = FailingCloseFiler()
    rep = reporter(filer, tmp_path)
    try:
        _file_then_close_subject(rep, apply=True)
    except RuntimeError as exc:
        assert "gh issue close failed" in str(exc)
    else:  # pragma: no cover - the whole point of the control
        raise AssertionError("a lost board write must surface, never be swallowed")
    assert ledger_keys(tmp_path) == {"lifecycle:VERIFY_EVIDENCE_MISSING:#1247"}


def test_resolve_without_close_only_comments(tmp_path):
    """The comment-only shape is still available for a caller that retires a
    fingerprint while the item is driven elsewhere (reconcile's shelved: key)."""
    filer = FakeFiler()
    rep = reporter(filer, tmp_path)
    rep.report("reconcile:shelved:#7", title="t", body="b", apply=True)
    assert rep.resolve("reconcile:shelved:#7", comment="landed", apply=True)
    assert filer.closed == []
    assert [entry["number"] for entry in filer.comments] == [2001]
    assert ledger_keys(tmp_path) == set()
    assert rep.resolve("reconcile:shelved:#7", comment="landed", apply=True) is False, "nothing left to resolve"


def test_the_audit_verb_retires_a_filed_finding_whose_invariant_cleared(tmp_path, monkeypatch, capsys):
    """#1299 end to end: ``lifecycle audit`` is where a finding filed by an earlier
    pass reaches its terminal state once the audit no longer charges it — on the
    hygienic path, which is exactly when every filed finding has cleared. Dry run
    names it (``would-resolve``); ``--apply`` closes the issue and retires the key."""
    import json

    from governance.lifecycle import cli

    filer = FakeFiler()
    rep = reporter(filer, tmp_path)
    monkeypatch.setattr(cli, "_reporter", lambda: rep)
    # An earlier pass filed BRANCH_NOT_DELETED for #269; the branch has since gone.
    rep.report("lifecycle:BRANCH_NOT_DELETED:#269", title="t", body="b", apply=True)
    recorded = tmp_path / "record.json"
    recorded.write_text(json.dumps(_conftest.record(clean_item())), encoding="utf-8")
    baseline = tmp_path / "baseline.json"
    baseline.write_text("{}", encoding="utf-8")

    assert cli.main(["audit", "--record", str(recorded), "--baseline", str(baseline)]) == 0
    out = capsys.readouterr().out
    assert "would-resolve" in out and "lifecycle:BRANCH_NOT_DELETED:#269" in out
    assert ledger_keys(tmp_path) == {"lifecycle:BRANCH_NOT_DELETED:#269"}, "a dry run retires nothing"

    assert cli.main(["audit", "--record", str(recorded), "--baseline", str(baseline), "--apply"]) == 0
    out = capsys.readouterr().out
    assert "resolved" in out
    assert [entry["number"] for entry in filer.closed] == [2001]
    assert ledger_keys(tmp_path) == set()
