"""Lane audit — the isolation contract, re-checked against the real worktree.

Provisioning establishes isolation once; this module re-derives it from the
filesystem and git every time it is asked. That is the difference between a
convention (someone was told to work in a worktree) and an institution (the
machine can prove it or refuse).

Three properties are checked, and each one is a real failure when broken:

* **the branch names the issue** — a lane whose branch does not encode the
  ticket is not linked to its issue at all;
* **the signature is the session's, and is lane-local** — a worktree whose
  identity is inherited, or whose signature landed in the shared config, would
  sign other lanes' commits as this session;
* **every commit this session authored carries the ticket trailer** — this is
  what ties generated history back to the issue, and it is checked per commit
  rather than per branch, because a branch that *mostly* references its ticket
  is exactly the drift the rule exists to stop.

The history rule is **positional**, and it has exactly one implementation in
this repository: the predicate inside ``scripts/check-pr-contract.sh`` (issue
#288). The reference must be a line of the message's *trailing trailer block* —
a mention in the subject line or in prose is not a trailer, and a message with
no trailer paragraph at all is the case the rule exists to refuse (issue #287,
measured on `6d89618` and `576edce`, whose only reference is their subject).
This module reaches that predicate through
:mod:`governance.isolation.trailer` rather than restating it, so the lane audit
and the PR gate cannot drift apart, and it refuses to report a lane as isolated
when the predicate cannot be run at all — an unassessable commit is not a clean
one.
"""

from __future__ import annotations

from pathlib import Path

from . import speculative
from .identity import SessionIdentity, branch_issue
from .trailer import PredicateUnavailable, classify_commit
from .violation import Violation
from .worktree import (
    git,
    is_linked_worktree,
    main_repo_root,
    read_stamped_identity,
    shared_identity,
)

__all__ = ["Violation", "audit_lane", "audit_all", "authored_commits", "trailer_violations"]

FIELD = "\x1f"
RECORD = "\x1e"


def _current_branch(worktree: Path) -> str:
    head = git(worktree, "symbolic-ref", "--short", "-q", "HEAD")
    return head.stdout.strip() if head.returncode == 0 else ""


def authored_commits(worktree: Path, email: str) -> list[str]:
    """The non-merge commits in this lane authored by ``email``, as shas.

    Selection is by *author identity*, not by branch range: the rule is that
    this session's generated history points at this session's ticket, and that
    holds whatever the branch was based on (and however often it was rebased).

    Merge commits are excluded, and that is a scope decision rather than an
    oversight: a merge message is generated by git rather than authored by the
    session, and the shared predicate audits ``--no-merges`` for precisely that
    reason (``scripts/check-pr-contract.sh --landed``). Requiring a trailer on a
    merge would be a local rule the shared predicate cannot express, and it
    would fail a lane for merging ``origin/master`` into its own branch — a
    commit whose message the session never writes. The exemption is documented
    in ``governance/isolation/README.md`` §4.

    The message itself is not returned: the verdict comes from the shared
    predicate, which reads the message from git (and classifies *position*,
    which a caller must not re-derive).
    """
    log = git(worktree, "log", "--no-merges", f"--format=%H{FIELD}%ae{RECORD}", "HEAD")
    if log.returncode != 0:
        return []
    shas = []
    for chunk in log.stdout.split(RECORD):
        if not chunk.strip():
            continue
        parts = chunk.strip("\n").split(FIELD, 1)
        if len(parts) != 2:
            continue
        sha, author_email = parts
        if author_email.strip() == email:
            shas.append(sha.strip())
    return shas


def trailer_violations(worktree: Path, identity: SessionIdentity) -> list[Violation]:
    """Commits this session authored that carry no ticket trailer where it counts.

    The rule is *position*, not presence: the reference must be a line of the
    message's trailing trailer block. The verdict is the shared predicate's
    (``governance/isolation/trailer.py``), never a substring test — a reference
    in the subject or in prose is a mention, not a trailer (issue #287).
    """
    untrailed: list[tuple[str, str]] = []
    unassessed: list[str] = []
    for sha in authored_commits(worktree, identity.author_email):
        try:
            finding = classify_commit(worktree, sha)
        except PredicateUnavailable as exc:
            unassessed.append(f"{sha[:8]} ({exc})")
            continue
        if finding:
            untrailed.append((sha, finding))

    problems: list[Violation] = []
    if untrailed:
        named = ", ".join(f"{sha[:8]} ({finding})" for sha, finding in untrailed[:5])
        if len(untrailed) > 5:
            named += f", +{len(untrailed) - 5} more"
        problems.append(
            Violation(
                "commit-missing-ticket-trailer",
                f"{len(untrailed)} commit(s) authored by {identity.author_email} lack "
                f"{identity.trailer!r} in their trailing trailer block, as named by the shared "
                f"predicate in scripts/check-pr-contract.sh: {named}",
            )
        )
    if unassessed:
        problems.append(
            Violation(
                "commit-trailer-check-unavailable",
                f"the shared trailer predicate could not assess {len(unassessed)} commit(s), so this "
                f"lane's history rule is unproven rather than satisfied: {', '.join(unassessed[:5])}",
            )
        )
    return problems


def audit_lane(identity: SessionIdentity, main: Path | str) -> list[Violation]:
    """Every isolation property this lane breaks (empty list = isolated)."""
    problems: list[Violation] = []
    worktree = identity.worktree

    encoded = branch_issue(identity.branch)
    if encoded != identity.issue:
        problems.append(
            Violation(
                "branch-does-not-name-issue",
                f"branch {identity.branch!r} does not encode issue #{identity.issue}",
            )
        )

    if not worktree.exists():
        problems.append(Violation("worktree-missing", f"{worktree} does not exist"))
        return problems
    if not is_linked_worktree(worktree):
        problems.append(Violation("worktree-not-linked", f"{worktree} is not a linked git worktree"))
        return problems

    current = _current_branch(worktree)
    if current != identity.branch:
        problems.append(
            Violation(
                "branch-mismatch",
                f"{worktree} is on {current or 'a detached HEAD'}, not the lane branch {identity.branch!r}",
            )
        )

    stamped = read_stamped_identity(worktree)
    if stamped is None:
        problems.append(
            Violation(
                "identity-not-lane-local",
                f"{worktree} carries no worktree-scoped signature; its commits would inherit another identity",
            )
        )
    elif stamped != (identity.author_name, identity.author_email):
        problems.append(
            Violation(
                "identity-mismatch",
                f"{worktree} signs as {stamped[0]} <{stamped[1]}>, not {identity.author_name} <{identity.author_email}>",
            )
        )

    shared = shared_identity(main_repo_root(main))
    if shared is not None and shared[1] == identity.author_email:
        problems.append(
            Violation(
                "identity-leaked-to-shared-config",
                f"the shared repository config signs as {identity.author_email}; every lane would inherit it",
            )
        )

    problems.extend(trailer_violations(worktree, identity))
    problems.extend(speculative.verify(main_repo_root(main), identity))
    return problems


def audit_all(main: Path | str) -> dict[str, list[Violation]]:
    """Audit every recorded lane; a lane id maps to its violations."""
    from .worktree import list_records

    return {identity.session_id: audit_lane(identity, main) for identity in list_records(main)}
