"""Read-only authority readers behind the enterprise (chat) tool family.

Issue kushin77/agent-orchestrator#504 (EPIC #500, "Chat grounding: the
read-only enterprise tool family + the citations envelope").

Every reader here **consumes an existing authority and returns it verbatim**,
stamped with that authority's own revision. Nothing in this module re-derives a
projection: ADR-0012 froze "a second projection is a second engine", and
ADR-0018 §3 froze "a shape that exists in a published contract is consumed,
never mirrored". So this module owns *no* state, writes *no* file, and asserts
*nothing* of its own about the facts it reads - it is a citation producer.

The authorities, one per family (all read on every call, so an edit on disk is
observed without a restart - the ``ao.bridge/v1`` property):

===============  ============================================================
family           authority
===============  ============================================================
``board``        ``.board/snapshot.json`` - the ticket join node (ADR-0014)
``budget``       ``telemetry/budgets/config/policies.yaml`` - declared policy
``ledger``       ``telemetry/ledger`` - consumed via ``telemetry.ledger.store``
``registry``     ``ao.bridge/v1`` ``registry`` family (``registry/profiles``)
``knowledge``    ``governance/knowledge/catalog.json`` - the real, in-repo
                 institutional-knowledge index (generated by its own indexer)
``codeidx``      ``kushin77/code-indexing`` - the real code-symbol index, which
                 is **not reachable from this repo**; declared here so the tool
                 says so instead of inventing an answer
``fleet``        ``ao.bridge/v1`` manifest + per-family revisions
``kb-fixture``   ``gateway/mcp/kb.py`` - the **declared fake** (ADR-0018 §2),
                 labelled ``fixture_only`` and refused on a production path
===============  ============================================================

**Honesty (AO-GR-19).** An absent or empty authority is never an empty
success: :class:`ReadResult` refuses to be constructed in the ``NO_DATA`` state
without a reason naming what was missing, and a ``fixture_only`` source is
refused by :class:`SourceCatalog` itself when the catalogue runs in production
mode - so a production grounding path cannot reach the declared fake index even
by mistake.
"""

from __future__ import annotations

import hashlib
import importlib
import json
import os
import sys
from dataclasses import dataclass, field
from typing import Any, Dict, List, Mapping, Optional, Sequence, Tuple

# --------------------------------------------------------------------------- #
# status + mode vocabulary (closed sets)
# --------------------------------------------------------------------------- #
STATUS_OK = "ok"
STATUS_NO_DATA = "NO_DATA"
STATUSES: Tuple[str, ...] = (STATUS_OK, STATUS_NO_DATA)

MODE_PRODUCTION = "production"
MODE_FIXTURE = "fixture"
MODES: Tuple[str, ...] = (MODE_PRODUCTION, MODE_FIXTURE)

#: Repo-relative home of every authority a family reads (the citation target).
BOARD_ARTIFACT = ".board/snapshot.json"
BUDGET_ARTIFACT = "telemetry/budgets/config/policies.yaml"
LEDGER_ARTIFACT = "telemetry/ledger"
REGISTRY_ARTIFACT = "registry/profiles"
KNOWLEDGE_ARTIFACT = "governance/knowledge/catalog.json"

#: The bridge contract the ``registry``/``fleet`` families are addressed by.
BRIDGE_CONTRACT = "ao.bridge/v1"

#: The real code-symbol index lives in another repo (ADR-0018 §1: code facts
#: are theirs). This is the reason returned when the family is asked anything.
CODEIDX_AUTHORITY = "kushin77/code-indexing (external compiler-accurate index)"
CODEIDX_UNAVAILABLE = (
    "the real code-symbol index is not reachable from this checkout: it is "
    "published by kushin77/code-indexing, which this repo lists as a mandatory "
    "consumer surface but cannot read offline (ADR-0018 §1/§4); the declared "
    "in-memory graph in gateway/mcp/kb.py is a fake and ADR-0018 §2 forbids it "
    "from backing a live path, so no code-symbol fact is asserted here"
)

#: Every ``fixture_only`` source is refused with this reason on a live path.
FIXTURE_REFUSAL = (
    "fixture-only authority refused on a production grounding path: "
    "%s is a declared fake (ADR-0018 §2/§3 - a fake answer standing in for a "
    "measured one is the false-green failure this fleet forbids); run the "
    "catalogue in fixture mode for offline work, or consume the real authority"
)

#: Argument names that would let a caller pick a tenant. Never declared by a
#: tool, and refused by name rather than ignored: an ignored scope selector
#: teaches a caller the wrong lesson, and a refusal is auditable.
TENANT_ARGUMENT_KEYS: Tuple[str, ...] = (
    "tenant", "tenant_id", "tenant-id", "tenantId", "tenantID",
)

#: Families whose reads run under a tenant (the rest are platform
#: configuration, readable by any authenticated principal - the bridge's rule).
#: The tenant is always taken from the verified session, never from a request.
TENANT_SCOPED_FAMILIES: Tuple[str, ...] = ("budget", "ledger", "kb-fixture")


class SourceUnavailable(Exception):
    """A declared authority is absent or unreadable where it should be read."""


def content_revision(data: bytes) -> str:
    """The authority's own revision: a content digest of what was read."""
    return hashlib.sha256(data).hexdigest()[:16]


# --------------------------------------------------------------------------- #
# read results (the citation-carrying envelope)
# --------------------------------------------------------------------------- #
@dataclass(frozen=True)
class Fragment:
    """One fact read from one authority, with the citation that names it.

    ``source_id`` is the stable identifier the citations envelope carries on to
    the UX lane: ``"<family>:<locator>@<revision>"``. ``revision`` is the
    digest of the authority *as read*, so the same locator on a changed
    authority is a different citation - never a silently recycled one.
    """

    family: str
    locator: str
    authority: str
    revision: str
    payload: Mapping[str, Any]

    @property
    def source_id(self) -> str:
        return f"{self.family}:{self.locator}@{self.revision}"

    def as_dict(self) -> Dict[str, Any]:
        return {
            "sourceId": self.source_id,
            "family": self.family,
            "locator": self.locator,
            "authority": self.authority,
            "revision": self.revision,
            "payload": dict(self.payload),
        }


@dataclass(frozen=True)
class ReadResult:
    """A family read: either fragments, or an explicit ``NO_DATA`` + reason.

    An empty result is **not** representable. ``NO_DATA`` without a reason
    raises at construction, and ``ok`` with no fragments raises too - an empty
    success is exactly the dishonesty AO-GR-19 names.
    """

    status: str
    fragments: Tuple[Fragment, ...] = ()
    reason: str = ""

    def __post_init__(self) -> None:
        if self.status not in STATUSES:
            raise ValueError(f"unknown read status {self.status!r}")
        if self.status == STATUS_NO_DATA:
            if not self.reason.strip():
                raise ValueError("NO_DATA requires a reason naming what was absent")
            if self.fragments:
                raise ValueError("NO_DATA never carries fragments")
        elif not self.fragments:
            raise ValueError("an ok read carries at least one fragment (never empty)")

    @property
    def is_ok(self) -> bool:
        return self.status == STATUS_OK

    @property
    def is_no_data(self) -> bool:
        return self.status == STATUS_NO_DATA

    def citations(self) -> Tuple[str, ...]:
        return tuple(fragment.source_id for fragment in self.fragments)

    @classmethod
    def ok(cls, fragments: Sequence[Fragment]) -> "ReadResult":
        return cls(status=STATUS_OK, fragments=tuple(fragments))

    @classmethod
    def no_data(cls, reason: str) -> "ReadResult":
        return cls(status=STATUS_NO_DATA, reason=reason)


# --------------------------------------------------------------------------- #
# the authority artifact reader (re-read on every call)
# --------------------------------------------------------------------------- #
class Artifact:
    """One repo-relative authority artifact, read fresh on every access."""

    def __init__(self, root: Any, relative: str) -> None:
        self.root = root
        self.relative = relative

    @property
    def path(self) -> str:
        return os.path.join(str(self.root), self.relative)

    def read_bytes(self) -> bytes:
        try:
            with open(self.path, "rb") as handle:
                return handle.read()
        except OSError as exc:
            raise SourceUnavailable(
                f"authority {self.relative} is unreadable in {self.root}: {exc}"
            ) from exc

    def read_json(self) -> Tuple[Any, str]:
        data = self.read_bytes()
        try:
            return json.loads(data.decode("utf-8")), content_revision(data)
        except ValueError as exc:
            raise SourceUnavailable(
                f"authority {self.relative} is not valid JSON: {exc}"
            ) from exc

    def read_yaml(self) -> Tuple[Any, str]:
        data = self.read_bytes()
        try:
            import yaml
        except Exception as exc:  # pragma: no cover - PyYAML ships with the repo
            raise SourceUnavailable(
                f"authority {self.relative} needs PyYAML to be read: {exc}"
            ) from exc
        try:
            return yaml.safe_load(data.decode("utf-8")), content_revision(data)
        except Exception as exc:
            raise SourceUnavailable(
                f"authority {self.relative} is not valid YAML: {exc}"
            ) from exc


# --------------------------------------------------------------------------- #
# the family sources
# --------------------------------------------------------------------------- #
class AuthoritySource:
    """A read-only family: an authority, an address, and no writable surface."""

    family: str = ""
    authority: str = ""
    fixture_only: bool = False

    def __init__(self, root: Any) -> None:
        self.root = root

    #: The operations this family publishes (name -> the tool that reads it).
    operations: Tuple[str, ...] = ()

    def perform(self, operation: str, **kwargs: Any) -> ReadResult:
        """Dispatch one declared operation (unknown ones are refused by name)."""
        if operation not in self.operations:
            return ReadResult.no_data(
                f"family {self.family!r} declares no read operation "
                f"{operation!r} (declared: {', '.join(self.operations)})"
            )
        handler = getattr(self, operation)
        return handler(**kwargs)


class BoardSource(AuthoritySource):
    """The ticket join node: ``.board/snapshot.json`` (ADR-0014).

    Reading the snapshot is reading the ticket; nothing here recomputes status,
    ``blocked_by`` or ``facets`` (ADR-0012). The payload carries the fields a
    citation may be held to - deliberately **not** ``closed_at``, because a
    timestamp in the cacheable static region is the exact token that kills a
    provider prefix cache (``engine/memory/prompt_cache.py``).
    """

    family = "board"
    authority = BOARD_ARTIFACT
    operations = ("ticket", "search")
    #: The issue fields a grounded fragment may carry (closed set).
    FIELDS: Tuple[str, ...] = (
        "number", "title", "state", "labels", "milestone", "parent", "blocked_by",
    )

    def _issues(self) -> Tuple[List[dict], str]:
        data, revision = Artifact(self.root, BOARD_ARTIFACT).read_json()
        issues = data.get("issues") if isinstance(data, dict) else None
        if not isinstance(issues, list):
            raise SourceUnavailable(
                f"authority {BOARD_ARTIFACT} carries no 'issues' list"
            )
        return issues, revision

    @classmethod
    def _payload(cls, issue: Mapping[str, Any]) -> Dict[str, Any]:
        return {key: issue.get(key) for key in cls.FIELDS if key in issue}

    def ticket(self, number: int) -> ReadResult:
        try:
            issues, revision = self._issues()
        except SourceUnavailable as exc:
            return ReadResult.no_data(str(exc))
        for issue in issues:
            if isinstance(issue, dict) and issue.get("number") == int(number):
                return ReadResult.ok([
                    Fragment(
                        family=self.family,
                        locator=f"#{int(number)}",
                        authority=self.authority,
                        revision=revision,
                        payload=self._payload(issue),
                    )
                ])
        return ReadResult.no_data(
            f"ticket #{int(number)} is absent from the board snapshot "
            f"{BOARD_ARTIFACT} (revision {revision}); it is not a ticket this "
            f"platform knows - no ticket is invented, and no other tenant's or "
            f"repo's board is consulted"
        )

    def search(
        self,
        *,
        text: Optional[str] = None,
        state: Optional[str] = None,
        label: Optional[str] = None,
        limit: int = 50,
    ) -> ReadResult:
        try:
            issues, revision = self._issues()
        except SourceUnavailable as exc:
            return ReadResult.no_data(str(exc))
        needle = (text or "").strip().lower()
        hits: List[Fragment] = []
        for issue in issues:
            if not isinstance(issue, dict):
                continue
            if state is not None and str(issue.get("state", "")).upper() != state.upper():
                continue
            if label is not None and label not in (issue.get("labels") or []):
                continue
            if needle and needle not in str(issue.get("title", "")).lower():
                continue
            hits.append(
                Fragment(
                    family=self.family,
                    locator=f"#{issue.get('number')}",
                    authority=self.authority,
                    revision=revision,
                    payload=self._payload(issue),
                )
            )
        hits.sort(key=lambda fragment: (len(fragment.locator), fragment.locator))
        if not hits:
            return ReadResult.no_data(
                "no ticket in the board snapshot matched "
                f"(text={text!r}, state={state!r}, label={label!r}) at revision "
                f"{revision}"
            )
        return ReadResult.ok(hits[: int(limit)])


class BudgetSource(AuthoritySource):
    """Declared budget policy: ``telemetry/budgets/config/policies.yaml``.

    What this family reads is the tenant's **declared** budget policy, labelled
    as such in the payload (``authorityKind: declared-policy``) so nobody
    mistakes a declared limit for measured spend. Measured spend lives in the
    metering feed (``telemetry/metering``), which this lane does not re-derive;
    a turn needing a measured figure must read that authority instead.
    """

    family = "budget"
    authority = BUDGET_ARTIFACT
    operations = ("status",)

    def status(self, tenant_id: str) -> ReadResult:
        try:
            data, revision = Artifact(self.root, BUDGET_ARTIFACT).read_yaml()
        except SourceUnavailable as exc:
            return ReadResult.no_data(str(exc))
        policies = data.get("policies") if isinstance(data, dict) else None
        if not isinstance(policies, list):
            return ReadResult.no_data(
                f"authority {BUDGET_ARTIFACT} declares no 'policies' list "
                f"(revision {revision})"
            )
        for policy in policies:
            if isinstance(policy, dict) and policy.get("tenantId") == tenant_id:
                payload = dict(policy)
                payload["authorityKind"] = "declared-policy"
                return ReadResult.ok([
                    Fragment(
                        family=self.family,
                        locator=str(tenant_id),
                        authority=self.authority,
                        revision=revision,
                        payload=payload,
                    )
                ])
        return ReadResult.no_data(
            f"tenant {tenant_id!r} has no declared budget policy in "
            f"{BUDGET_ARTIFACT} (revision {revision}); the file's defaultMode is "
            f"{data.get('defaultMode')!r}, which is a declared default rather "
            f"than this tenant's budget - no budget is inferred"
        )


class LedgerSource(AuthoritySource):
    """The tenant's tamper-evident ledger, consumed via its own store.

    ``telemetry/ledger/store.py`` is the authority's own reader: it re-parses
    the tenant's JSON Lines file on every call, so an external edit is observed
    and a broken chain is *detected* rather than described. ``verify`` carries
    the store's tri-state verdict verbatim (OK / NOT-OK / CANNOT-ASSESS) - a
    verdict is data, never a summary this lane computes.
    """

    family = "ledger"
    authority = LEDGER_ARTIFACT
    operations = ("tail", "verify")

    def _store(self) -> Tuple[Optional[Any], str]:
        directory = os.path.join(str(self.root), LEDGER_ARTIFACT)
        if not os.path.isdir(directory):
            # Never create it: ``LedgerStore.__init__`` would ``makedirs`` the
            # path, and this family is read-only. An absent authority is NO_DATA.
            return None, (
                f"the ledger authority {LEDGER_ARTIFACT} is absent from this "
                f"checkout, and this read-only family does not create it: no "
                f"chain is attested where there is no store"
            )
        try:
            if str(self.root) not in sys.path:
                sys.path.insert(0, str(self.root))
            module = importlib.import_module("telemetry.ledger.store")
            store = module.LedgerStore(directory=directory)
        except Exception as exc:  # a missing authority is NO_DATA, never a crash
            return None, (
                f"the ledger authority {LEDGER_ARTIFACT} is not consumable from "
                f"this checkout: {exc}"
            )
        return store, ""

    def tail(self, tenant_id: str, *, limit: int = 20) -> ReadResult:
        store, reason = self._store()
        if store is None:
            return ReadResult.no_data(reason)
        try:
            records = store.records(tenant_id)
            seq, tail_hash = store.tail_state(tenant_id)
        except Exception as exc:
            return ReadResult.no_data(
                f"tenant {tenant_id!r}'s ledger chain is unreadable: {exc}"
            )
        if not records:
            return ReadResult.no_data(
                f"tenant {tenant_id!r} has no ledger chain in {LEDGER_ARTIFACT} "
                f"(no record has been appended yet); an absent chain is reported "
                f"as absent, never as an intact empty one"
            )
        window = records[-int(limit):]
        return ReadResult.ok([
            Fragment(
                family=self.family,
                locator=f"{tenant_id}:seq{record.get('seq')}",
                authority=self.authority,
                revision=content_revision(json.dumps(record, sort_keys=True).encode("utf-8")),
                payload={
                    "tenantId": tenant_id,
                    "seq": record.get("seq"),
                    "ts": record.get("ts"),
                    "actor": record.get("actor"),
                    "action": record.get("action"),
                    "resource": record.get("resource"),
                    "chainTail": {"seq": seq, "hash": tail_hash},
                    "recordCount": len(records),
                },
            )
            for record in window
        ])

    def verify(self, tenant_id: str) -> ReadResult:
        store, reason = self._store()
        if store is None:
            return ReadResult.no_data(reason)
        try:
            verdict = store.verify(tenant_id)
        except Exception as exc:
            return ReadResult.no_data(
                f"tenant {tenant_id!r}'s ledger chain cannot be judged: {exc}"
            )
        payload = verdict.as_dict()
        if payload.get("status") == "OK" and payload.get("seq") in (0, None):
            # The store's own genesis tail means "no records yet", not "intact".
            return ReadResult.no_data(
                f"tenant {tenant_id!r} has no ledger chain to verify in "
                f"{LEDGER_ARTIFACT}: there is nothing to attest, so nothing is "
                f"attested (the store reports its genesis tail, status "
                f"{payload.get('status')!r} at seq {payload.get('seq')!r})"
            )
        return ReadResult.ok([
            Fragment(
                family=self.family,
                locator=f"{tenant_id}",
                authority=self.authority,
                revision=str(payload.get("hash", ""))[:16],
                payload=payload,
            )
        ])


class RegistrySource(AuthoritySource):
    """The agent roster, consumed through the versioned bridge family.

    ``ao.bridge/v1`` (``docs/LIVE-DATA-BRIDGE.md``, issue #339) is the versioned
    address; it delegates to ``registry/profiles`` and publishes the family's
    own ``revision``, which is the citation here. Nothing is restated: this
    family holds no profile copy and computes no tier.
    """

    family = "registry"
    authority = REGISTRY_ARTIFACT
    operations = ("list", "status")

    def __init__(self, root: Any, *, bridge: Any = None) -> None:
        super().__init__(root)
        self._bridge = bridge
        self.fixture_only = bool(getattr(bridge, "fixture_only", False)) if bridge else False

    def _read(self) -> Tuple[Optional[Mapping[str, Any]], str]:
        try:
            if self._bridge is not None:
                bridge = self._bridge
            else:
                if str(self.root) not in sys.path:
                    sys.path.insert(0, str(self.root))
                bridge = importlib.import_module("portal.server.bridge").LiveBridge(
                    repo_root=self.root
                )
            payload = bridge.registry()
        except Exception as exc:
            return None, (
                f"the {BRIDGE_CONTRACT} 'registry' family is unavailable from "
                f"this checkout: {exc}"
            )
        if not isinstance(payload, Mapping) or payload.get("available") is False:
            return None, (
                f"the {BRIDGE_CONTRACT} 'registry' family reports no readable "
                f"source at {REGISTRY_ARTIFACT}"
            )
        return payload, ""

    def list(self, *, limit: int = 50) -> ReadResult:
        payload, reason = self._read()
        if payload is None:
            return ReadResult.no_data(reason)
        profiles = payload.get("profiles") or []
        if not profiles:
            return ReadResult.no_data(
                f"the {BRIDGE_CONTRACT} 'registry' family carries no profile "
                f"seeds at revision {payload.get('revision')!r}"
            )
        revision = str(payload.get("revision", ""))
        return ReadResult.ok([
            Fragment(
                family=self.family,
                locator=str(profile.get("id", "")),
                authority=BRIDGE_CONTRACT,
                revision=revision,
                payload=dict(profile),
            )
            for profile in profiles[: int(limit)]
        ])

    def status(self, agent_id: str) -> ReadResult:
        payload, reason = self._read()
        if payload is None:
            return ReadResult.no_data(reason)
        for profile in payload.get("profiles") or []:
            if profile.get("id") == agent_id:
                return ReadResult.ok([
                    Fragment(
                        family=self.family,
                        locator=str(agent_id),
                        authority=BRIDGE_CONTRACT,
                        revision=str(payload.get("revision", "")),
                        payload=dict(profile),
                    )
                ])
        return ReadResult.no_data(
            f"agent {agent_id!r} is not in the {BRIDGE_CONTRACT} 'registry' "
            f"family at revision {payload.get('revision')!r}; an unknown agent "
            f"is reported absent, never defaulted to another profile"
        )


class KnowledgeSource(AuthoritySource):
    """The real, in-repo institutional-knowledge index (issue #139).

    ``governance/knowledge/catalog.json`` is generated by
    ``governance/knowledge/indexer.py`` from declared sources and carries
    per-item provenance (origin repo, path, version, sha256, owner). This is a
    **real** index surface reachable from this checkout, so it is the one the
    chat path grounds on. The fragment payload is the item's provenance - no
    ``generated_at``, no item ``timestamp``: a volatile value in the cacheable
    prefix is the token that kills provider caching.
    """

    family = "knowledge"
    authority = KNOWLEDGE_ARTIFACT
    operations = ("query", "coverage")

    def _index(self) -> Tuple[Optional[Mapping[str, Any]], str]:
        """Return ``(index, revision)`` on success, ``(None, reason)`` otherwise."""
        try:
            data, revision = Artifact(self.root, KNOWLEDGE_ARTIFACT).read_json()
        except SourceUnavailable as exc:
            return None, (
                f"{exc}; build it with 'python3 governance/knowledge/cli.py build' "
                f"- an unbuilt index is reported as NO_DATA, never as an empty "
                f"catalogue"
            )
        if not isinstance(data, Mapping) or not isinstance(data.get("items"), list):
            return None, (
                f"authority {KNOWLEDGE_ARTIFACT} carries no 'items' list "
                f"(revision {revision})"
            )
        return data, revision

    @staticmethod
    def _payload(item: Mapping[str, Any]) -> Dict[str, Any]:
        provenance = item.get("provenance") or {}
        return {
            "id": item.get("id"),
            "kind": item.get("kind"),
            "title": item.get("title"),
            "path": item.get("path"),
            "owner": provenance.get("owner"),
            "version": provenance.get("version"),
            "sha256": provenance.get("sha256"),
            "originRepo": provenance.get("origin_repo"),
        }

    def query(
        self,
        *,
        text: Optional[str] = None,
        kind: Optional[str] = None,
        limit: int = 20,
    ) -> ReadResult:
        data, revision_or_reason = self._index()
        if data is None:
            return ReadResult.no_data(revision_or_reason)
        revision = revision_or_reason
        needle = (text or "").strip().lower()
        hits: List[Fragment] = []
        for item in data["items"]:
            if not isinstance(item, Mapping):
                continue
            if kind is not None and item.get("kind") != kind:
                continue
            haystack = " ".join(
                str(item.get(field, "")) for field in ("id", "title", "path")
            )
            haystack += " " + " ".join(str(tag) for tag in item.get("tags") or [])
            if needle and needle not in haystack.lower():
                continue
            hits.append(
                Fragment(
                    family=self.family,
                    locator=str(item.get("id", "")),
                    authority=self.authority,
                    revision=revision,
                    payload=self._payload(item),
                )
            )
        hits.sort(key=lambda fragment: fragment.locator)
        if not hits:
            return ReadResult.no_data(
                f"no indexed knowledge item matched (text={text!r}, kind={kind!r}) "
                f"in {KNOWLEDGE_ARTIFACT} at revision {revision}"
            )
        return ReadResult.ok(hits[: int(limit)])

    def coverage(self) -> ReadResult:
        data, revision_or_reason = self._index()
        if data is None:
            return ReadResult.no_data(revision_or_reason)
        revision = revision_or_reason
        entries = data.get("coverage") or []
        fragments = []
        for entry in entries:
            if not isinstance(entry, Mapping):
                continue
            fragments.append(
                Fragment(
                    family=self.family,
                    locator=f"coverage:{entry.get('kind')}",
                    authority=self.authority,
                    revision=revision,
                    payload={
                        "kind": entry.get("kind"),
                        "status": entry.get("status"),
                        "count": entry.get("count"),
                        "required": entry.get("required"),
                        "reason": entry.get("reason"),
                    },
                )
            )
        fragments.sort(key=lambda fragment: fragment.locator)
        if not fragments:
            return ReadResult.no_data(
                f"authority {KNOWLEDGE_ARTIFACT} reports no coverage entries at "
                f"revision {revision}"
            )
        return ReadResult.ok(fragments)


class CodeIndexSource(AuthoritySource):
    """The real code-symbol index, declared and honestly unreachable.

    ADR-0018 §1 splits authorities: code facts belong to
    ``kushin77/code-indexing``, institutional facts to
    ``governance/knowledge``. That vendor surface is not readable from this
    checkout, so every operation returns ``NO_DATA`` naming why, rather than
    answering from a local fake. The seam exists so the *tool says so* and the
    turn degrades explicitly (issue #504, honesty requirement).
    """

    family = "codeidx"
    authority = CODEIDX_AUTHORITY
    operations = ("query", "freshness", "definitions")

    def query(self, **_: Any) -> ReadResult:  # noqa: D102 - see class docstring
        return ReadResult.no_data(CODEIDX_UNAVAILABLE)

    def freshness(self, **_: Any) -> ReadResult:  # noqa: D102 - see class docstring
        return ReadResult.no_data(CODEIDX_UNAVAILABLE)

    def definitions(self, **_: Any) -> ReadResult:  # noqa: D102 - see class docstring
        return ReadResult.no_data(CODEIDX_UNAVAILABLE)


class KbFixtureSource(AuthoritySource):
    """The **declared fake** per-tenant index, labelled fixture-only.

    ``gateway/mcp/kb.py`` documents itself as an in-memory declared graph with no
    real indexer behind it, and ADR-0018 §2 keeps it as the offline fixture
    only. This source is therefore ``fixture_only``: :class:`SourceCatalog`
    refuses it on a production path before any read happens, so a live
    grounding answer can never come from the fake.
    """

    family = "kb-fixture"
    authority = "gateway/mcp/kb.py (declared fake per ADR-0018 §2)"
    operations = ("query", "freshness")
    fixture_only = True

    def __init__(self, root: Any, *, backend: Any = None) -> None:
        super().__init__(root)
        self._backend = backend

    def _backend_or_none(self) -> Optional[Any]:
        if self._backend is not None:
            return self._backend
        try:
            if str(self.root) not in sys.path:
                sys.path.insert(0, str(self.root))
            module = importlib.import_module("gateway.mcp.kb")
            return module.KbRegistry().backend_for("fixture-tenant")
        except Exception:
            return None

    def query(self, *, repo: Optional[str] = None, module_id: Optional[str] = None) -> ReadResult:
        backend = self._backend_or_none()
        if backend is None:
            return ReadResult.no_data(
                "the fixture index backend is not importable in this checkout"
            )
        payload = backend.query(module_id=module_id, repo=repo)
        return ReadResult.ok([
            Fragment(
                family=self.family,
                locator=str(repo or module_id or "fixture"),
                authority=self.authority,
                revision=content_revision(json.dumps(payload, sort_keys=True).encode("utf-8")),
                payload=payload,
            )
        ])

    def freshness(self, *, repo: str) -> ReadResult:
        backend = self._backend_or_none()
        if backend is None:
            return ReadResult.no_data(
                "the fixture index backend is not importable in this checkout"
            )
        payload = backend.freshness(repo)
        return ReadResult.ok([
            Fragment(
                family=self.family,
                locator=str(repo),
                authority=self.authority,
                revision=content_revision(json.dumps(payload, sort_keys=True).encode("utf-8")),
                payload=payload,
            )
        ])


class FleetSource(AuthoritySource):
    """The ``ao.bridge/v1`` manifest + per-family revisions (a change signal).

    One fragment per bridge family, whose ``revision`` is the bridge's own
    content digest of that family's source - the citation form the ticket asks
    for ("bridge family + revision"). The push channel is a signal, not a data
    channel, so this family carries revisions and the manifest rows, and never a
    payload copy of another family.
    """

    family = "fleet"
    authority = BRIDGE_CONTRACT
    operations = ("snapshot",)

    def __init__(self, root: Any, *, bridge: Any = None) -> None:
        super().__init__(root)
        self._bridge = bridge
        self.fixture_only = bool(getattr(bridge, "fixture_only", False)) if bridge else False

    def snapshot(self) -> ReadResult:
        try:
            if self._bridge is not None:
                bridge = self._bridge
            else:
                if str(self.root) not in sys.path:
                    sys.path.insert(0, str(self.root))
                bridge = importlib.import_module("portal.server.bridge").LiveBridge(
                    repo_root=self.root
                )
            manifest = bridge.manifest()
            revisions = bridge.revisions()
        except Exception as exc:
            return ReadResult.no_data(
                f"the {BRIDGE_CONTRACT} manifest is unavailable from this "
                f"checkout: {exc}"
            )
        rows = manifest.get("families") if isinstance(manifest, Mapping) else None
        if not isinstance(rows, list) or not rows:
            return ReadResult.no_data(
                f"the {BRIDGE_CONTRACT} manifest declares no family rows"
            )
        fragments = []
        for row in rows:
            if not isinstance(row, Mapping):
                continue
            family_id = str(row.get("id", ""))
            fragments.append(
                Fragment(
                    family=self.family,
                    locator=family_id,
                    authority=BRIDGE_CONTRACT,
                    revision=str(revisions.get(family_id, "")),
                    payload={
                        "id": family_id,
                        "source": row.get("source"),
                        "path": row.get("path"),
                        "kind": row.get("kind"),
                        "contract": manifest.get("contract"),
                    },
                )
            )
        fragments.sort(key=lambda fragment: fragment.locator)
        if not fragments:
            return ReadResult.no_data(
                f"the {BRIDGE_CONTRACT} manifest declares no readable family row"
            )
        return ReadResult.ok(fragments)


# --------------------------------------------------------------------------- #
# the catalogue: the single gate every family read passes through
# --------------------------------------------------------------------------- #
@dataclass
class SourceCatalog:
    """The declared read-only families, read through one fail-closed gate.

    The catalogue - not the caller - decides what may be read: an unknown family
    and a ``fixture_only`` family on a production path both yield ``NO_DATA``
    with a reason, so a tool can never widen its own scope by asking.
    """

    root: Any
    mode: str = MODE_PRODUCTION
    _sources: Dict[str, AuthoritySource] = field(default_factory=dict)

    def __post_init__(self) -> None:
        if self.mode not in MODES:
            raise ValueError(f"unknown catalogue mode {self.mode!r}")

    # -- construction ---------------------------------------------------- #
    @classmethod
    def from_repo_root(
        cls,
        root: Any,
        *,
        mode: str = MODE_PRODUCTION,
        bridge: Any = None,
    ) -> "SourceCatalog":
        """The declared catalogue over ``root``.

        ``bridge`` is the ``ao.bridge/v1`` read surface the ``registry`` and
        ``fleet`` families consume. It defaults to the real
        ``portal.server.bridge.LiveBridge`` over ``root``; injecting a fixture
        bridge is how an offline test exercises those families - and because a
        fixture bridge is labelled ``fixture_only``, the catalogue refuses it on
        a production path regardless of who supplied it.
        """
        catalog = cls(root=root, mode=mode)
        catalog.add(BoardSource(root))
        catalog.add(BudgetSource(root))
        catalog.add(LedgerSource(root))
        catalog.add(RegistrySource(root, bridge=bridge))
        catalog.add(KnowledgeSource(root))
        catalog.add(CodeIndexSource(root))
        catalog.add(FleetSource(root, bridge=bridge))
        return catalog

    def add(self, source: AuthoritySource) -> "SourceCatalog":
        if source.family in self._sources:
            raise ValueError(f"duplicate source for family {source.family!r}")
        self._sources[source.family] = source
        return self

    # -- read surface ----------------------------------------------------- #
    def families(self) -> Tuple[str, ...]:
        return tuple(sorted(self._sources))

    def source(self, family: str) -> AuthoritySource:
        return self._sources[family]

    def is_fixture_only(self, family: str) -> bool:
        return bool(self._sources[family].fixture_only)

    def call(self, family: str, operation: str, **kwargs: Any) -> ReadResult:
        """Read one operation of one family (fail closed, never a fallback)."""
        source = self._sources.get(family)
        if source is None:
            return ReadResult.no_data(
                f"no read-only source is declared for family {family!r} "
                f"(declared families: {', '.join(self.families())})"
            )
        if source.fixture_only and self.mode == MODE_PRODUCTION:
            return ReadResult.no_data(FIXTURE_REFUSAL % family)
        try:
            return source.perform(operation, **kwargs)
        except SourceUnavailable as exc:
            return ReadResult.no_data(str(exc))


def default_repo_root() -> str:
    """The checkout this package is installed in (gateway/mcp -> repo root)."""
    return os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
