#!/usr/bin/env bash
# ============================================================================
# scripts/check-fleet-drift.sh
#
# Owner-lane: fleet / watchdog
# Class: enterprise
# Connects-to: consumes=fleet/channel.py,fleet/watchdog.py,fleet/health.py; gates=AO-GR-25
# ============================================================================
#
# AO-GR-4 / AO-GR-25: this check must be able to genuinely FAIL, and it must
# prove that about itself. The defect it exists for was measured on 2026-09-14:
# the sister loop (pid 17797, started 19:18Z) executed code from before a fix
# that merged at ~23:00Z, while the watchdog logged `sister: healthy` on every
# tick — because it compared the loop's heartbeat commit to
# `channel.head_commit()`, the *shared checkout*, which was itself behind. Both
# sides were the same stale commit, so drift was structurally invisible.
#
# The companion defect: the rule was guarded by `head != "unknown"`, so an
# unreadable HEAD silently disabled drift detection instead of reporting that it
# could not run. A control that fails open is worse than none.
#
# What this proves, against the real classifier (never a re-implementation):
#   1. running == the LOCAL checkout (stale) but != origin/master  ⇒ drifted
#      This is the exact measured case, and it is the self-control: the run
#      below pins `head_commit()` to the *running* commit, so the only way to
#      reach `drifted` is to compare against the remote.
#   2. an unreadable baseline                                        ⇒ cannot-assess
#   3. running == origin/master                                      ⇒ current
#   4. the watchdog's operator line names BOTH commits
#   5. MUTATION PROOF: a mutant that restores the local-HEAD comparison must be
#      caught. The mutant is generated by rewriting the real source in a scratch
#      copy of the tree, and the same probe must then FAIL — a check that cannot
#      fail is a formality.
#
# Tri-state contract (docs/QA-GATE.md):
#   0 OK             — every case classified correctly and the mutant is caught
#   1 NOT-OK         — a case is misclassified, or the mutant survived
#   2 CANNOT-ASSESS  — the code under test cannot be imported (never a pass)
#
# ---knowledge---
# module_id: scripts.check-fleet-drift
# system: governance
# app: gates
# solution_class: enterprise
# patterns: [tri-state-exit, provoked-negative-control, no-false-green]
# derives_from: null
# owner_sme: platform-sme
# tier: L1
# interfaces: [exit 0 OK, exit 1 NOT-OK, exit 2 CANNOT-ASSESS]
# invariants: ""
# gotchas: ""
# related: []
# do_not_duplicate: null
# ---knowledge---
set -uo pipefail

source "$(dirname "${BASH_SOURCE[0]}")/lib/common.sh"
ROOT="$(find_repo_root)" || exit 2

fail=0
note() { printf '  %-6s %s\n' "$1" "$2"; }
bad() { note "FAIL" "$1"; fail=1; }
ok() { note "OK" "$1"; }

if [ ! -f "$ROOT/fleet/channel.py" ] || [ ! -f "$ROOT/fleet/watchdog.py" ]; then
  echo "check-fleet-drift: CANNOT-ASSESS — fleet/channel.py or fleet/watchdog.py is unreadable" >&2
  exit 2
fi

if ! command -v python3 >/dev/null 2>&1; then
  echo "check-fleet-drift: CANNOT-ASSESS — python3 is not on PATH" >&2
  exit 2
fi

# Scratch tree for the mutation proof. A unique template (never a bare
# `mktemp -d`): $TMPDIR is a shared, periodically-cleaned cache on this box, and
# a copy that vanishes mid-run reports a failure that is not the code's.
work="$(mktemp -d "/tmp/ao-drift.$(date +%s).$$."$(printf 'X%.0s' 1 2 3 4 5 6))" || exit 2
trap 'rm -rf "$work"' EXIT

# --- 1. the classifier contract, against the REAL module ----------------------
#
# One probe, run twice: once against the working tree, once against the mutant.
# It exercises `channel.classify_drift` and `watchdog.decide` — the two functions
# that carried the defect — and never a re-implementation of them.
cat > "$work/probe.py" <<'PROBE'
"""Classify the measured cases through the real drift classifier."""
import sys

root = sys.argv[1]
sys.path.insert(0, f"{root}/fleet")

# A stale __pycache__ can shadow the tree under test and make a mutant invisible
# (measured: two different mutations produced byte-identical output). Refuse to
# write bytecode and prove the import really resolved in the tree we asked for.
sys.dont_write_bytecode = True

import channel  # noqa: E402

if not channel.__file__.startswith(root):
    print(f"IMPORT-ESCAPED {channel.__file__}", file=sys.stderr)
    sys.exit(9)

import watchdog  # noqa: E402

if not watchdog.__file__.startswith(root):
    print(f"IMPORT-ESCAPED {watchdog.__file__}", file=sys.stderr)
    sys.exit(9)


def beat_age(_beat, moment=None):
    return 10.0


channel.heartbeat_age_seconds = beat_age
watchdog.channel.heartbeat_age_seconds = beat_age

# The measured facts: the loop and the shared checkout are the SAME stale commit
# (592b132); origin/master is ahead (47a068b).
STALE = "592b132"
REMOTE = "47a068b"

cases = {}

# (1) THE measured case. A classifier that consults the local checkout reaches
# `healthy` here — the defect. Only a remote comparison reaches `drifted`.
cases["local_stale_masquerade"] = channel.classify_drift(STALE, REMOTE)[0]
cases["decide_local_stale_masquerade"] = watchdog.decide(
    111, {"pid": 111, "state": "idle", "commit": STALE}, REMOTE
)[0]

# (2) fail-closed: an unreadable baseline is never healthy.
cases["unreadable_baseline"] = channel.classify_drift(STALE, "unknown")[0]
cases["decide_unreadable_baseline"] = watchdog.decide(
    111, {"pid": 111, "state": "idle", "commit": STALE}, "unknown"
)[0]

# (3) genuinely current.
cases["current"] = channel.classify_drift(REMOTE, REMOTE)[0]

# (4) the reason names both commits.
_, reason = channel.classify_drift(STALE, REMOTE)
cases["reason_names_both"] = "ok" if (STALE in reason and REMOTE in reason) else "bad"

# (5) the local checkout is not consulted at all: whatever `head_commit()`
# returns must not change the verdict.
channel.head_commit = lambda: STALE
cases["ignores_local_head"] = channel.classify_drift(STALE, REMOTE)[0]

for name, value in cases.items():
    print(f"{name}={value}")
PROBE

run_probe() { # run_probe <root> <logfile>
  env PYTHONDONTWRITEBYTECODE=1 python3 "$work/probe.py" "$1" > "$2" 2>&1
}

# --- mutation proof: build a scratch tree whose classifier uses the local HEAD -

# The mutant rewrites the REAL drift comparison so the baseline becomes the local
# checkout — exactly the pre-#739 rule. Everything else is the current source, so
# the only difference is the defect.
mr="$work/mutant"
mkdir -p "$mr" || exit 2
copy_tree() { # copy_tree <dest> — the modules the fleet package imports at import time
  for part in fleet governance; do
    [ -e "$ROOT/$part" ] || continue
    cp -R "$ROOT/$part" "$1/$part" 2>/dev/null || return 1
  done
  # A stale __pycache__ carried into the copy would shadow the mutated source,
  # and an escaped import would make the control vacuous (measured: two different
  # mutations once produced byte-identical gate output this way).
  find "$1" -name '__pycache__' -type d -prune -exec rm -rf {} + 2>/dev/null || true
  return 0
}
copy_tree "$mr" || {
  echo "check-fleet-drift: CANNOT-ASSESS — cannot copy the fleet tree for the mutant" >&2
  exit 2
}

python3 - "$mr/fleet/channel.py" <<'MUTATE'
"""Restore the pre-fix comparison: classify against the local checkout."""
import pathlib
import sys

path = pathlib.Path(sys.argv[1])
source = path.read_text(encoding="utf-8")
needle = "    if running == baseline:"
if needle not in source:
    print("MUTATE-FAILED", file=sys.stderr)
    sys.exit(1)
# The mutant ignores its `baseline` argument and consults the local HEAD, which
# is the defect in one line.
mutant = source.replace(
    needle,
    "    baseline = head_commit()  # MUTANT: the pre-#739 local-checkout baseline\n"
    "    if running == baseline:",
    1,
)
if mutant == source:
    print("MUTATE-FAILED", file=sys.stderr)
    sys.exit(1)
path.write_text(mutant, encoding="utf-8")
print("MUTATED")
MUTATE
mutate_rc=$?
if [ "$mutate_rc" -ne 0 ]; then
  bad "the mutation could not be constructed (the classifier source moved)"
  echo "check-fleet-drift: FAIL — the self-control could not run" >&2
  exit 1
fi

echo "== the classifier (real source) =="
run_probe "$ROOT" "$work/real.out"
real_rc=$?
if [ "$real_rc" -eq 9 ]; then
  echo "check-fleet-drift: CANNOT-ASSESS — the probe imported a module outside the tree under test" >&2
  sed 's/^/    /' "$work/real.out" >&2
  exit 2
fi
if [ "$real_rc" -ne 0 ]; then
  echo "check-fleet-drift: CANNOT-ASSESS — the probe could not run against the real source" >&2
  sed 's/^/    /' "$work/real.out" >&2
  exit 2
fi
sed 's/^/    /' "$work/real.out"

expect() { # expect <case> <want> [<file>]
  local got
  got="$(grep -F "$1=" "${3:-$work/real.out}" | head -1 | cut -d= -f2-)"
  if [ -z "$got" ]; then
    bad "$1 produced no verdict (the classifier did not run)"
    return 1
  fi
  if [ "$got" != "$2" ]; then
    bad "$1 ⇒ $got (want $2)"
    return 1
  fi
  return 0
}

# (1) THE regression. Both entry points must report drift for the measured case.
expect "local_stale_masquerade" "drifted" &&
  expect "decide_local_stale_masquerade" "drifted" &&
  ok "running == the local (stale) checkout but != origin/master ⇒ drifted"

# (2) fail-closed.
expect "unreadable_baseline" "cannot-assess" &&
  expect "decide_unreadable_baseline" "cannot-assess" &&
  ok "an unreadable origin/master baseline ⇒ cannot-assess, never healthy"

# (3) current is still current.
expect "current" "ok" && ok "running == origin/master ⇒ ok"

# (4) both commits named.
expect "reason_names_both" "ok" && ok "the drift reason names the running and the remote commit"

# (5) the local checkout is not consulted.
expect "ignores_local_head" "drifted" && ok "the local HEAD is not consulted at all"

# --- the mutation proof -------------------------------------------------------

echo "== the mutant (pre-#739 local-HEAD baseline) =="
run_probe "$mr" "$work/mutant.out"
mutant_rc=$?
if [ "$mutant_rc" -eq 9 ]; then
  echo "check-fleet-drift: CANNOT-ASSESS — the mutant probe imported outside its tree" >&2
  exit 2
fi
sed 's/^/    /' "$work/mutant.out"

# The mutants all share the property that the *local checkout* decides the
# verdict. Two probe cases discriminate that directly and are independent of how
# the mutant is spelled:
#   * `current` (running == origin/master) must be `ok`. The local-HEAD mutant
#     compares running to the local checkout instead, so it reports `drifted`.
#   * `ignores_local_head` must be `drifted` (the local HEAD is pinned to the
#     running commit, the remote is ahead). The local-HEAD mutant reports `ok`.
# Either divergence proves the mutant was caught; the surviving mutant is the
# one that reproduces the real verdicts on both.
mutant_current="$(grep -F 'current=' "$work/mutant.out" | head -1 | cut -d= -f2-)"
mutant_ignores="$(grep -F 'ignores_local_head=' "$work/mutant.out" | head -1 | cut -d= -f2-)"
if [ "$mutant_current" != "ok" ] || [ "$mutant_ignores" != "drifted" ]; then
  ok "the local-HEAD mutant is caught (current=$mutant_current, local-HEAD=$mutant_ignores)"
else
  bad "the local-HEAD mutant SURVIVED — it reproduces the real verdicts; this check cannot fail"
fi

# A second, independent mutant: restore the `head != "unknown"` fail-open guard,
# which turned an unreadable baseline into a silent pass.
mr2="$work/mutant-failopen"
mkdir -p "$mr2" || exit 2
copy_tree "$mr2" || {
  echo "check-fleet-drift: CANNOT-ASSESS — cannot copy the fleet tree for the second mutant" >&2
  exit 2
}
python3 - "$mr2/fleet/channel.py" <<'MUTATE2'
"""Restore the fail-open guard: `unknown` baseline reads as healthy."""
import pathlib
import sys

path = pathlib.Path(sys.argv[1])
source = path.read_text(encoding="utf-8")
needle = '    if not known_baseline:'
if needle not in source:
    print("MUTATE-FAILED", file=sys.stderr)
    sys.exit(1)
mutant = source.replace(
    needle,
    '    if False:  # MUTANT: the pre-#739 fail-open guard\n    # if not known_baseline:',
    1,
)
if mutant == source:
    print("MUTATE-FAILED", file=sys.stderr)
    sys.exit(1)
path.write_text(mutant, encoding="utf-8")
print("MUTATED")
MUTATE2
if [ $? -ne 0 ]; then
  bad "the fail-open mutation could not be constructed"
else
  echo "== the second mutant (fail-open on an unknown baseline) =="
  run_probe "$mr2" "$work/mutant2.out"
  if grep -qF "IMPORT-ESCAPED" "$work/mutant2.out"; then
    bad "the second mutant imported a module outside its tree — the control is vacuous"
  else
    sed 's/^/    /' "$work/mutant2.out"
    open_verdict="$(grep -F "unreadable_baseline=" "$work/mutant2.out" | head -1 | cut -d= -f2-)"
    if [ "$open_verdict" = "cannot-assess" ]; then
      bad "the fail-open mutant SURVIVED — an unreadable baseline still reads cannot-assess"
    else
      ok "the fail-open mutant is caught (an unreadable baseline reads $open_verdict)"
    fi
  fi
fi

# --- the operator line names both commits (requirement 3) ---------------------

line_out="$(env PYTHONDONTWRITEBYTECODE=1 python3 - "$ROOT" <<'LINE'
import sys
import tempfile
from pathlib import Path

root = sys.argv[1]
sys.path.insert(0, f"{root}/fleet")
sys.dont_write_bytecode = True

import channel  # noqa: E402
import watchdog  # noqa: E402

# `rung_action` persists its bounded-remedy ledger under FLEET_DIR (#773), so a
# probe that drives it must point that ledger at a scratch directory: a check
# may not write runtime state into the tree it is testing.
watchdog.FLEET_DIR = Path(tempfile.mkdtemp(prefix="ao-drift-probe-"))
channel.heartbeat_age_seconds = lambda beat, moment=None: 10.0
watchdog.channel.heartbeat_age_seconds = lambda beat, moment=None: 10.0
watchdog.loop_pid = lambda pattern: 111
watchdog.read_beat = lambda path: {"pid": 111, "state": "idle", "commit": "592b132"}
watchdog.respawn = lambda *a, **k: True
channel.capability_line = lambda finding: f"{finding.rung}: {finding.case}"

print(
    watchdog.rung_action(
        "brain",
        "fleet/brain.py",
        "fleet/brain.sh",
        __import__("pathlib").Path("/tmp/x"),
        False,
        "47a068b",
    )
)
LINE
)"
if grep -qF "running 592b132" <<<"$line_out" && grep -qF "origin/master 47a068b" <<<"$line_out"; then
  ok "the watchdog line names both commits: $line_out"
else
  bad "the watchdog line does not name both commits: $line_out"
fi

# --- the exit-code contract ---------------------------------------------------

exit_rc="$(env PYTHONDONTWRITEBYTECODE=1 python3 - "$ROOT" <<'RC' | tail -1
import sys
import tempfile
from pathlib import Path

root = sys.argv[1]
sys.path.insert(0, f"{root}/fleet")
sys.dont_write_bytecode = True

import channel  # noqa: E402
import watchdog  # noqa: E402

# Same reason as above: `watchdog_once` now records a bounded remedy per rung
# (#773), and this probe must not leave that ledger in the tested tree.
watchdog.FLEET_DIR = Path(tempfile.mkdtemp(prefix="ao-drift-rc-"))
channel.remote_head_commit = lambda: "unknown"
watchdog.loop_pid = lambda pattern: 111
watchdog.channel.heartbeat_age_seconds = lambda beat, moment=None: 10.0
watchdog.read_beat = lambda path: {"pid": 111, "state": "idle", "commit": "592b132"}
watchdog.respawn = lambda *a, **k: True
watchdog.monitor_missing = lambda: False
# The rung lines go to stdout; only the exit code is the verdict, so it is
# printed last and read with `tail -1`.
watchdog.watchdog_once()
print(f"RC={watchdog.watchdog_once()}")
RC
)"
if [ "$exit_rc" = "RC=2" ]; then
  ok "an unjudgeable pass exits 2 (CANNOT-ASSESS), never 0"
else
  bad "an unjudgeable pass exited '$exit_rc', want RC=2 — the control still fails open"
fi

if [ "$fail" -eq 0 ]; then
  echo "check-fleet-drift: OK — drift is measured against origin/master and never fails open"
  exit 0
fi
echo "check-fleet-drift: FAIL" >&2
exit 1
